import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/context/theme-provider'
import { ReactNode } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

type Layout = {
  children: ReactNode
  modal: ReactNode
}

export default function RootLayout({ children, modal }: Layout) {
  return (
    <>
      <html lang="ja" suppressHydrationWarning={true}>
        <head />
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            {modal}
          </ThemeProvider>
        </body>
      </html>
    </>
  )
}
